const actionTypes = {
    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',

    GET_POSTS: 'GET_POSTS',
    GET_POSTS_LIMIT: 'GET_POSTS_LIMIT',
    GET_POSTS_ADMIN: 'GET_POSTS_ADMIN',
    EDIT_DATA: 'EDIT_DATA',
    RESET_DATAEDIT: 'RESET_DATAEDIT',

    GET_CATEGORIES: 'GET_CATEGORIES',
    GET_PRICES: 'GET_PRICES',
    GET_AREAS: 'GET_AREAS',
    GET_NEW_POSTS: 'GET_NEW_POSTS',
    GET_OUTSTANDING_POSTS: 'GET_OUTSTANDING_POSTS',
    GET_PROVINCES: 'GET_PROVINCES',
    GET_CURRENT: 'GET_CURRENT',
    GET_POST_LIKE: 'GET_POST_LIKE',



}


export default actionTypes